name: leons blog
url: http://leontheawesomecoder-github.io
description: Learn about hackers
permalink: /themes/:title/

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
